server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: file-storage-service
          uri: http://file-storage-service:9001
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://file-analysis-service:9090
          predicates:
            - Path=/analysis/**
        - id: swagger-ui
          uri: http://file-storage-service:9001
          predicates:
            - Path=/swagger-ui/**
        - id: api-docs
          uri: http://file-storage-service:9001
          predicates:
            - Path=/v3/api-docs/**
      discovery:
        locator:
          enabled: false

springdoc:
  swagger-ui:
    urls:
      - name: file-storage-service
        url: http://localhost:9001/v3/api-docs
      - name: file-analysis-service 
        url: http://localhost:9090/v3/api-docs
